package insight

// Copyright (c) Park MinKeun and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"context"
	"net/http"

	"github.com/Azure/go-autorest/autorest"
	"github.com/Azure/go-autorest/autorest/azure"
	"github.com/Azure/go-autorest/tracing"
)

// ServerClient is the cloud Insight Client
type ServerClient struct {
	BaseClient
}

// NewServerClient creates an instance of the ServerClient client.
func NewServerClient() ServerClient {
	return NewServerClientWithBaseURI(DefaultBaseURI)
}

// NewServerClientWithBaseURI creates an instance of the ServerClient client.
func NewServerClientWithBaseURI(baseURI string) ServerClient {
	return ServerClient{NewWithBaseURI(baseURI)}
}

// CreatTop target metric (mem_usert/avg_cpu_user_rto/fs_usert)
// Parameters:
// query - target metric (mem_usert/avg_cpu_user_rto/fs_usert)
func (client ServerClient) CreatTop(ctx context.Context, query string) (result autorest.Response, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/ServerClient.CreatTop")
		defer func() {
			sc := -1
			if result.Response != nil {
				sc = result.Response.StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	req, err := client.CreatTopPreparer(ctx, query)
	if err != nil {
		err = autorest.NewErrorWithError(err, "insight.ServerClient", "CreatTop", nil, "Failure preparing request")
		return
	}

	resp, err := client.CreatTopSender(req)
	if err != nil {
		result.Response = resp
		err = autorest.NewErrorWithError(err, "insight.ServerClient", "CreatTop", resp, "Failure sending request")
		return
	}

	result, err = client.CreatTopResponder(resp)
	if err != nil {
		err = autorest.NewErrorWithError(err, "insight.ServerClient", "CreatTop", resp, "Failure responding to request")
	}

	return
}

// CreatTopPreparer prepares the CreatTop request.
func (client ServerClient) CreatTopPreparer(ctx context.Context, query string) (*http.Request, error) {
	queryParameters := map[string]interface{}{}
	if len(query) > 0 {
		queryParameters["query"] = autorest.Encode("query", query)
	}

	preparer := autorest.CreatePreparer(
		autorest.AsPost(),
		autorest.WithBaseURL(client.BaseURI),
		autorest.WithPath("/cw_fea/real/cw/api/servers/top"),
		autorest.WithQueryParameters(queryParameters))
	return preparer.Prepare((&http.Request{}).WithContext(ctx))
}

// CreatTopSender sends the CreatTop request. The method will close the
// http.Response Body if it receives an error.
func (client ServerClient) CreatTopSender(req *http.Request) (*http.Response, error) {
	sd := autorest.GetSendDecorators(req.Context(), autorest.DoRetryForStatusCodes(client.RetryAttempts, client.RetryDuration, autorest.StatusCodesForRetry...))
	return autorest.SendWithSender(client, req, sd...)
}

// CreatTopResponder handles the response to the CreatTop request. The method always
// closes the http.Response Body.
func (client ServerClient) CreatTopResponder(resp *http.Response) (result autorest.Response, err error) {
	err = autorest.Respond(
		resp,
		client.ByInspecting(),
		azure.WithErrorUnlessStatusCode(http.StatusOK),
		autorest.ByClosing())
	result.Response = resp
	return
}
