package insightapi

// Copyright (c) Park MinKeun and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"context"

	"github.com/Azure/go-autorest/autorest"
	"github.com/samjegal/fincloud-sdk-for-go/services/insight"
)

// DataClientAPI contains the set of methods on the DataClient type.
type DataClientAPI interface {
	Preview(ctx context.Context) (result autorest.Response, err error)
	Query(ctx context.Context) (result autorest.Response, err error)
	QueryMultiple(ctx context.Context) (result autorest.Response, err error)
}

var _ DataClientAPI = (*insight.DataClient)(nil)

// EventClientAPI contains the set of methods on the EventClient type.
type EventClientAPI interface {
	SearchEventCount(ctx context.Context) (result autorest.Response, err error)
}

var _ EventClientAPI = (*insight.EventClient)(nil)

// RuleClientAPI contains the set of methods on the RuleClient type.
type RuleClientAPI interface {
	Create(ctx context.Context) (result autorest.Response, err error)
	Delete(ctx context.Context, ruleID string) (result autorest.Response, err error)
	Get(ctx context.Context, ruleID string) (result autorest.Response, err error)
	GetList(ctx context.Context, pageNum string, pageSize string) (result autorest.Response, err error)
	Update(ctx context.Context, ruleID string) (result autorest.Response, err error)
}

var _ RuleClientAPI = (*insight.RuleClient)(nil)

// SchemaClientAPI contains the set of methods on the SchemaClient type.
type SchemaClientAPI interface {
	Create(ctx context.Context, prodName string) (result autorest.Response, err error)
	Delete(ctx context.Context, prodName string) (result autorest.Response, err error)
	Disable(ctx context.Context, cwKey string, instanceIds string) (result autorest.Response, err error)
	Enable(ctx context.Context, cwKey string, instanceIds string) (result autorest.Response, err error)
	Get(ctx context.Context, prodName string) (result autorest.Response, err error)
	GetList(ctx context.Context) (result autorest.Response, err error)
	QueryStatus(ctx context.Context, cwKey string, instanceIds string) (result autorest.Response, err error)
	Update(ctx context.Context, prodName string) (result autorest.Response, err error)
}

var _ SchemaClientAPI = (*insight.SchemaClient)(nil)

// ServerClientAPI contains the set of methods on the ServerClient type.
type ServerClientAPI interface {
	CreatTop(ctx context.Context, query string) (result autorest.Response, err error)
}

var _ ServerClientAPI = (*insight.ServerClient)(nil)
