// +build go1.9

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/samjegal/fincloud-sdk-for-go/tools/profileBuilder

package nas

import original "github.com/samjegal/fincloud-sdk-for-go/services/nas"

const (
	DefaultBaseURI = original.DefaultBaseURI
)

type EncryptedVolume = original.EncryptedVolume

const (
	False EncryptedVolume = original.False
	True  EncryptedVolume = original.True
)

type EventConfiguration = original.EventConfiguration

const (
	EventConfigurationFalse EventConfiguration = original.EventConfigurationFalse
	EventConfigurationTrue  EventConfiguration = original.EventConfigurationTrue
)

type SnapshotConfiguration = original.SnapshotConfiguration

const (
	SnapshotConfigurationFalse SnapshotConfiguration = original.SnapshotConfigurationFalse
	SnapshotConfigurationTrue  SnapshotConfiguration = original.SnapshotConfigurationTrue
)

type SortedBy = original.SortedBy

const (
	NasVolumeInstanceNo SortedBy = original.NasVolumeInstanceNo
	VolumeName          SortedBy = original.VolumeName
	VolumeTotalSize     SortedBy = original.VolumeTotalSize
)

type SortingOrder = original.SortingOrder

const (
	ASC  SortingOrder = original.ASC
	DESC SortingOrder = original.DESC
)

type VolumeAllotmentProtocolTypeCode = original.VolumeAllotmentProtocolTypeCode

const (
	CIFS VolumeAllotmentProtocolTypeCode = original.CIFS
	NFS  VolumeAllotmentProtocolTypeCode = original.NFS
)

type BaseClient = original.BaseClient
type Client = original.Client
type VolumeAccessControlAddResponse = original.VolumeAccessControlAddResponse
type VolumeAccessControlAddResponseAddNasVolumeAccessControlResponse = original.VolumeAccessControlAddResponseAddNasVolumeAccessControlResponse
type VolumeAccessControlRemoveResponse = original.VolumeAccessControlRemoveResponse
type VolumeAccessControlRemoveResponseRemoveNasVolumeAccessControlResponse = original.VolumeAccessControlRemoveResponseRemoveNasVolumeAccessControlResponse
type VolumeAccessControlSetResponse = original.VolumeAccessControlSetResponse
type VolumeAccessControlSetResponseSetNasVolumeAccessControlResponse = original.VolumeAccessControlSetResponseSetNasVolumeAccessControlResponse
type VolumeAllotmentProtocolType = original.VolumeAllotmentProtocolType
type VolumeInstanceDetailResponse = original.VolumeInstanceDetailResponse
type VolumeInstanceDetailResponseGetNasVolumeInstanceDetailResponse = original.VolumeInstanceDetailResponseGetNasVolumeInstanceDetailResponse
type VolumeInstanceList = original.VolumeInstanceList
type VolumeInstanceListResponse = original.VolumeInstanceListResponse
type VolumeInstanceListResponseGetNasVolumeInstanceListResponse = original.VolumeInstanceListResponseGetNasVolumeInstanceListResponse
type VolumeInstanceOperation = original.VolumeInstanceOperation
type VolumeInstanceStatus = original.VolumeInstanceStatus
type VolumeInstancesCreateResponse = original.VolumeInstancesCreateResponse
type VolumeInstancesCreateResponseCreateNasVolumeInstanceResponse = original.VolumeInstancesCreateResponseCreateNasVolumeInstanceResponse
type VolumeInstancesDeleteResponse = original.VolumeInstancesDeleteResponse
type VolumeInstancesDeleteResponseDeleteNasVolumeInstancesResponse = original.VolumeInstancesDeleteResponseDeleteNasVolumeInstancesResponse
type VolumeSizeResponse = original.VolumeSizeResponse
type VolumeSizeResponseChangeNasVolumeSizeResponse = original.VolumeSizeResponseChangeNasVolumeSizeResponse

func New() BaseClient {
	return original.New()
}
func NewClient() Client {
	return original.NewClient()
}
func NewClientWithBaseURI(baseURI string) Client {
	return original.NewClientWithBaseURI(baseURI)
}
func NewWithBaseURI(baseURI string) BaseClient {
	return original.NewWithBaseURI(baseURI)
}
func PossibleEncryptedVolumeValues() []EncryptedVolume {
	return original.PossibleEncryptedVolumeValues()
}
func PossibleEventConfigurationValues() []EventConfiguration {
	return original.PossibleEventConfigurationValues()
}
func PossibleSnapshotConfigurationValues() []SnapshotConfiguration {
	return original.PossibleSnapshotConfigurationValues()
}
func PossibleSortedByValues() []SortedBy {
	return original.PossibleSortedByValues()
}
func PossibleSortingOrderValues() []SortingOrder {
	return original.PossibleSortingOrderValues()
}
func PossibleVolumeAllotmentProtocolTypeCodeValues() []VolumeAllotmentProtocolTypeCode {
	return original.PossibleVolumeAllotmentProtocolTypeCodeValues()
}
func UserAgent() string {
	return original.UserAgent() + " profiles/latest"
}
func Version() string {
	return original.Version()
}
