package outboundmailer

// Copyright (c) Park MinKeun and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/Azure/go-autorest/autorest"
)

// The package's fully qualified name.
const fqdn = "github.com/samjegal/fincloud-sdk-for-go/services/outboundmailer"

// RecipientForRequest 수신자 요청 정보
type RecipientForRequest struct {
	// Address - 수신자 Email 주소
	Address *string `json:"address,omitempty"`
	// Name - 수신자 이름
	Name *string `json:"name,omitempty"`
	// Type - 수신자 유형 (R: 수신자, C: 참조인, B: 숨은참조)
	Type *string `json:"type,omitempty"`
	// Parameters - 치환 파라미터 (수신자별로 적용), '치환 ID' 를 key로, '치환 ID에 맵핑되는 값' 을 value로 가지는 Map 형태의 Object
	Parameters *RecipientForRequestParameters `json:"parameters,omitempty"`
}

// RecipientForRequestParameters 치환 파라미터 (수신자별로 적용), '치환 ID' 를 key로, '치환 ID에 맵핑되는 값' 을 value로 가지는 Map 형태의
// Object
type RecipientForRequestParameters struct {
	// CustomerName - 고객 이름
	CustomerName *string `json:"customer_name,omitempty"`
	// BEFOREGRADE - 등급 (BRONZE, SILVER, GOLD)
	BEFOREGRADE *string `json:"BEFORE_GRADE,omitempty"`
	// AFTERGRADE - 등급 (BRONZE, SILVER, GOLD)
	AFTERGRADE *string `json:"AFTER_GRADE,omitempty"`
}

// RecipientGroupFilter 수신자 그룹 조합 필터
type RecipientGroupFilter struct {
	// AndFilter - AND 조합 여부 (true : AND 조합, false : OR 조합)
	AndFilter *bool `json:"andFilter,omitempty"`
	// Groups - 수신자 그룹명 목록
	Groups *[]string `json:"groups,omitempty"`
}

// RequestParameter ...
type RequestParameter struct {
	// SenderAddress - 발송자 Email 주소
	SenderAddress *string `json:"senderAddress,omitempty"`
	// SenderName - 발송자 이름
	SenderName *string `json:"senderName,omitempty"`
	// TemplateSid - 템플릿 ID
	TemplateSid *int32 `json:"templateSid,omitempty"`
	// Title - 메일 제목
	Title *string `json:"title,omitempty"`
	// Body - 메일 본문
	Body *string `json:"body,omitempty"`
	// Individual - 개인발송여부
	Individual *bool `json:"individual,omitempty"`
	// ConfirmAndSend - 확인 후 발송 여부
	ConfirmAndSend *bool `json:"confirmAndSend,omitempty"`
	// Advertising - 광고메일여부
	Advertising *bool `json:"advertising,omitempty"`
	// Parameters - 치환 파라미터
	Parameters interface{} `json:"parameters,omitempty"`
	// ReferencesHeader - 특정 메일을 모아서 보기 위해 네이버 메일에서 지원하는 기능
	ReferencesHeader *string `json:"referencesHeader,omitempty"`
	// ReservationUtc - 예약 발송 일시
	ReservationUtc *float64 `json:"reservationUtc,omitempty"`
	// ReservationDateTime - 예약 발송 일시, reservationUtc 값이 우선
	ReservationDateTime *string `json:"reservationDateTime,omitempty"`
	// AttachFileIds - 첨부파일 ID 목록
	AttachFileIds *[]string `json:"attachFileIds,omitempty"`
	// Recipients - 수신자 목록
	Recipients *[]RecipientForRequest `json:"recipients,omitempty"`
	// RecipientGroupFilter - 수신자 그룹 조합 발송 조건
	RecipientGroupFilter interface{} `json:"recipientGroupFilter,omitempty"`
	// UseBasicUnsubscribeMsg - 광고 메일일 경우 기본 수신 거부 문구 사용 여부
	UseBasicUnsubscribeMsg *bool `json:"useBasicUnsubscribeMsg,omitempty"`
	// UnsubscribeMessage - 사용자 정의 수신 거부 문구
	UnsubscribeMessage *string `json:"unsubscribeMessage,omitempty"`
}

// ResponseParameter ...
type ResponseParameter struct {
	autorest.Response `json:"-"`
	// RequestID - 메일 발송 요청 ID
	RequestID *string `json:"requestId,omitempty"`
	// Count - 메일 요청 건수
	Count *int32 `json:"count,omitempty"`
}
