// +build go1.9

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/samjegal/fincloud-sdk-for-go/tools/profileBuilder

package kubernetes

import original "github.com/samjegal/fincloud-sdk-for-go/services/kubernetes"

const (
	DefaultBaseURI = original.DefaultBaseURI
)

type AutoscaleOptionParameter = original.AutoscaleOptionParameter
type AutoscalerUpdateParameter = original.AutoscalerUpdateParameter
type BaseClient = original.BaseClient
type ClusterParamter = original.ClusterParamter
type ClusterRequest = original.ClusterRequest
type ClusterResponse = original.ClusterResponse
type ClustersClient = original.ClustersClient
type ClustersListResponse = original.ClustersListResponse
type ConfigClient = original.ConfigClient
type ConfigResponse = original.ConfigResponse
type DefaultNodePoolParameter = original.DefaultNodePoolParameter
type NodePoolClient = original.NodePoolClient
type NodePoolParameter = original.NodePoolParameter
type NodePoolRequest = original.NodePoolRequest
type NodePoolResponse = original.NodePoolResponse
type NodePoolUpdateRequest = original.NodePoolUpdateRequest
type WorkerNodeClient = original.WorkerNodeClient
type WorkerNodeParameter = original.WorkerNodeParameter
type WorkerNodeResponse = original.WorkerNodeResponse

func New() BaseClient {
	return original.New()
}
func NewClustersClient() ClustersClient {
	return original.NewClustersClient()
}
func NewClustersClientWithBaseURI(baseURI string) ClustersClient {
	return original.NewClustersClientWithBaseURI(baseURI)
}
func NewConfigClient() ConfigClient {
	return original.NewConfigClient()
}
func NewConfigClientWithBaseURI(baseURI string) ConfigClient {
	return original.NewConfigClientWithBaseURI(baseURI)
}
func NewNodePoolClient() NodePoolClient {
	return original.NewNodePoolClient()
}
func NewNodePoolClientWithBaseURI(baseURI string) NodePoolClient {
	return original.NewNodePoolClientWithBaseURI(baseURI)
}
func NewWithBaseURI(baseURI string) BaseClient {
	return original.NewWithBaseURI(baseURI)
}
func NewWorkerNodeClient() WorkerNodeClient {
	return original.NewWorkerNodeClient()
}
func NewWorkerNodeClientWithBaseURI(baseURI string) WorkerNodeClient {
	return original.NewWorkerNodeClientWithBaseURI(baseURI)
}
func UserAgent() string {
	return original.UserAgent() + " profiles/latest"
}
func Version() string {
	return original.Version()
}
