// +build go1.9

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/samjegal/fincloud-sdk-for-go/tools/profileBuilder

package outboundmailer

import original "github.com/samjegal/fincloud-sdk-for-go/services/outboundmailer"

const (
	DefaultBaseURI = original.DefaultBaseURI
)

type BaseClient = original.BaseClient
type MailClient = original.MailClient
type RecipientForRequest = original.RecipientForRequest
type RecipientForRequestParameters = original.RecipientForRequestParameters
type RecipientGroupFilter = original.RecipientGroupFilter
type RequestParameter = original.RequestParameter
type ResponseParameter = original.ResponseParameter

func New() BaseClient {
	return original.New()
}
func NewMailClient() MailClient {
	return original.NewMailClient()
}
func NewMailClientWithBaseURI(baseURI string) MailClient {
	return original.NewMailClientWithBaseURI(baseURI)
}
func NewWithBaseURI(baseURI string) BaseClient {
	return original.NewWithBaseURI(baseURI)
}
func UserAgent() string {
	return original.UserAgent() + " profiles/latest"
}
func Version() string {
	return original.Version()
}
