// +build go1.9

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/samjegal/fincloud-sdk-for-go/tools/profileBuilder

package insight

import original "github.com/samjegal/fincloud-sdk-for-go/services/insight"

const (
	DefaultBaseURI = original.DefaultBaseURI
)

type BaseClient = original.BaseClient
type DataClient = original.DataClient
type EventClient = original.EventClient
type RuleClient = original.RuleClient
type SchemaClient = original.SchemaClient
type ServerClient = original.ServerClient

func New() BaseClient {
	return original.New()
}
func NewDataClient() DataClient {
	return original.NewDataClient()
}
func NewDataClientWithBaseURI(baseURI string) DataClient {
	return original.NewDataClientWithBaseURI(baseURI)
}
func NewEventClient() EventClient {
	return original.NewEventClient()
}
func NewEventClientWithBaseURI(baseURI string) EventClient {
	return original.NewEventClientWithBaseURI(baseURI)
}
func NewRuleClient() RuleClient {
	return original.NewRuleClient()
}
func NewRuleClientWithBaseURI(baseURI string) RuleClient {
	return original.NewRuleClientWithBaseURI(baseURI)
}
func NewSchemaClient() SchemaClient {
	return original.NewSchemaClient()
}
func NewSchemaClientWithBaseURI(baseURI string) SchemaClient {
	return original.NewSchemaClientWithBaseURI(baseURI)
}
func NewServerClient() ServerClient {
	return original.NewServerClient()
}
func NewServerClientWithBaseURI(baseURI string) ServerClient {
	return original.NewServerClientWithBaseURI(baseURI)
}
func NewWithBaseURI(baseURI string) BaseClient {
	return original.NewWithBaseURI(baseURI)
}
func UserAgent() string {
	return original.UserAgent() + " profiles/latest"
}
func Version() string {
	return original.Version()
}
