// +build go1.9

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/samjegal/fincloud-sdk-for-go/tools/profileBuilder

package location

import original "github.com/samjegal/fincloud-sdk-for-go/services/location"

const (
	DefaultBaseURI = original.DefaultBaseURI
)

type BaseClient = original.BaseClient
type RegionClient = original.RegionClient
type RegionParameter = original.RegionParameter
type RegionProperties = original.RegionProperties
type ZoneClient = original.ZoneClient
type ZoneParameter = original.ZoneParameter
type ZoneProperties = original.ZoneProperties

func New() BaseClient {
	return original.New()
}
func NewRegionClient() RegionClient {
	return original.NewRegionClient()
}
func NewRegionClientWithBaseURI(baseURI string) RegionClient {
	return original.NewRegionClientWithBaseURI(baseURI)
}
func NewWithBaseURI(baseURI string) BaseClient {
	return original.NewWithBaseURI(baseURI)
}
func NewZoneClient() ZoneClient {
	return original.NewZoneClient()
}
func NewZoneClientWithBaseURI(baseURI string) ZoneClient {
	return original.NewZoneClientWithBaseURI(baseURI)
}
func UserAgent() string {
	return original.UserAgent() + " profiles/latest"
}
func Version() string {
	return original.Version()
}
