// +build go1.9

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/samjegal/fincloud-sdk-for-go/tools/profileBuilder

package computeapi

import original "github.com/samjegal/fincloud-sdk-for-go/services/compute/computeapi"

type BlockStorageClientAPI = original.BlockStorageClientAPI
type InboundRuleClientAPI = original.InboundRuleClientAPI
type InitScriptClientAPI = original.InitScriptClientAPI
type LoginKeyClientAPI = original.LoginKeyClientAPI
type NetworkInterfaceClientAPI = original.NetworkInterfaceClientAPI
type OutboundRuleClientAPI = original.OutboundRuleClientAPI
type PublicIPAddressClientAPI = original.PublicIPAddressClientAPI
type RootPasswordClientAPI = original.RootPasswordClientAPI
type SecurityGroupClientAPI = original.SecurityGroupClientAPI
type SecurityGroupRuleClientAPI = original.SecurityGroupRuleClientAPI
type ServerClientAPI = original.ServerClientAPI
type ServerContractRestrictionClientAPI = original.ServerContractRestrictionClientAPI
type ServerImageClientAPI = original.ServerImageClientAPI
type StorageClientAPI = original.StorageClientAPI
