// +build go1.9

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/samjegal/fincloud-sdk-for-go/tools/profileBuilder

package registry

import original "github.com/samjegal/fincloud-sdk-for-go/services/registry"

const (
	DefaultBaseURI = original.DefaultBaseURI
)

type RepositoryStatus = original.RepositoryStatus

const (
	Disconnected RepositoryStatus = original.Disconnected
	Running      RepositoryStatus = original.Running
)

type BaseClient = original.BaseClient
type ContainerRegistryClient = original.ContainerRegistryClient
type ContainerRegistryImageClient = original.ContainerRegistryImageClient
type ImageTagResultImagesItem = original.ImageTagResultImagesItem
type ImageTagResultItem = original.ImageTagResultItem
type MessageResponse = original.MessageResponse
type Permissions = original.Permissions
type RepositoryGetListResponse = original.RepositoryGetListResponse
type RepositoryImageDetailResponse = original.RepositoryImageDetailResponse
type RepositoryImageItem = original.RepositoryImageItem
type RepositoryImageListResponse = original.RepositoryImageListResponse
type RepositoryImageTagListResponse = original.RepositoryImageTagListResponse
type RepositoryImageTagReferenceResponse = original.RepositoryImageTagReferenceResponse
type RepositoryRequest = original.RepositoryRequest
type RepositoryResultItem = original.RepositoryResultItem
type SetObject = original.SetObject
type UpdateRepositoryImageRequest = original.UpdateRepositoryImageRequest

func New() BaseClient {
	return original.New()
}
func NewContainerRegistryClient() ContainerRegistryClient {
	return original.NewContainerRegistryClient()
}
func NewContainerRegistryClientWithBaseURI(baseURI string) ContainerRegistryClient {
	return original.NewContainerRegistryClientWithBaseURI(baseURI)
}
func NewContainerRegistryImageClient() ContainerRegistryImageClient {
	return original.NewContainerRegistryImageClient()
}
func NewContainerRegistryImageClientWithBaseURI(baseURI string) ContainerRegistryImageClient {
	return original.NewContainerRegistryImageClientWithBaseURI(baseURI)
}
func NewWithBaseURI(baseURI string) BaseClient {
	return original.NewWithBaseURI(baseURI)
}
func PossibleRepositoryStatusValues() []RepositoryStatus {
	return original.PossibleRepositoryStatusValues()
}
func UserAgent() string {
	return original.UserAgent() + " profiles/latest"
}
func Version() string {
	return original.Version()
}
