package compute

// Copyright (c) Park MinKeun and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"context"
	"net/http"

	"github.com/Azure/go-autorest/autorest"
	"github.com/Azure/go-autorest/autorest/azure"
	"github.com/Azure/go-autorest/tracing"
)

// LoginKeysClient is the compute Client
type LoginKeysClient struct {
	BaseClient
}

// NewLoginKeysClient creates an instance of the LoginKeysClient client.
func NewLoginKeysClient() LoginKeysClient {
	return NewLoginKeysClientWithBaseURI(DefaultBaseURI)
}

// NewLoginKeysClientWithBaseURI creates an instance of the LoginKeysClient client.
func NewLoginKeysClientWithBaseURI(baseURI string) LoginKeysClient {
	return LoginKeysClient{NewWithBaseURI(baseURI)}
}

// List 인증키 확인
func (client LoginKeysClient) List(ctx context.Context, infraResourceTypeCode string, instanceName string, blockStorageUsageTypeCode string) (result LoginKeyContentParameter, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/LoginKeysClient.List")
		defer func() {
			sc := -1
			if result.Response.Response != nil {
				sc = result.Response.Response.StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	req, err := client.ListPreparer(ctx, infraResourceTypeCode, instanceName, blockStorageUsageTypeCode)
	if err != nil {
		err = autorest.NewErrorWithError(err, "compute.LoginKeysClient", "List", nil, "Failure preparing request")
		return
	}

	resp, err := client.ListSender(req)
	if err != nil {
		result.Response = autorest.Response{Response: resp}
		err = autorest.NewErrorWithError(err, "compute.LoginKeysClient", "List", resp, "Failure sending request")
		return
	}

	result, err = client.ListResponder(resp)
	if err != nil {
		err = autorest.NewErrorWithError(err, "compute.LoginKeysClient", "List", resp, "Failure responding to request")
	}

	return
}

// ListPreparer prepares the List request.
func (client LoginKeysClient) ListPreparer(ctx context.Context, infraResourceTypeCode string, instanceName string, blockStorageUsageTypeCode string) (*http.Request, error) {
	queryParameters := map[string]interface{}{
		"blockStorageUsageTypeCode": autorest.Encode("query", blockStorageUsageTypeCode),
		"infraResourceTypeCode":     autorest.Encode("query", infraResourceTypeCode),
		"instanceName":              autorest.Encode("query", instanceName),
	}

	preparer := autorest.CreatePreparer(
		autorest.AsGet(),
		autorest.WithBaseURL(client.BaseURI),
		autorest.WithPath("/vpc-compute/api/compute/v1/login-keys"),
		autorest.WithQueryParameters(queryParameters))
	return preparer.Prepare((&http.Request{}).WithContext(ctx))
}

// ListSender sends the List request. The method will close the
// http.Response Body if it receives an error.
func (client LoginKeysClient) ListSender(req *http.Request) (*http.Response, error) {
	sd := autorest.GetSendDecorators(req.Context(), autorest.DoRetryForStatusCodes(client.RetryAttempts, client.RetryDuration, autorest.StatusCodesForRetry...))
	return autorest.SendWithSender(client, req, sd...)
}

// ListResponder handles the response to the List request. The method always
// closes the http.Response Body.
func (client LoginKeysClient) ListResponder(resp *http.Response) (result LoginKeyContentParameter, err error) {
	err = autorest.Respond(
		resp,
		client.ByInspecting(),
		azure.WithErrorUnlessStatusCode(http.StatusOK),
		autorest.ByUnmarshallingJSON(&result),
		autorest.ByClosing())
	result.Response = autorest.Response{Response: resp}
	return
}
