// +build go1.9

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/samjegal/fincloud-sdk-for-go/tools/profileBuilder

package sens

import original "github.com/samjegal/fincloud-sdk-for-go/services/sens"

const (
	DefaultBaseURI = original.DefaultBaseURI
)

type AlimTalkMessageRequestParameter = original.AlimTalkMessageRequestParameter
type AlimTalkMessageRequestParameterMessagesItem = original.AlimTalkMessageRequestParameterMessagesItem
type AlimTalkMessageRequestParameterMessagesPropertiesItemsItem = original.AlimTalkMessageRequestParameterMessagesPropertiesItemsItem
type AlimTalkMessageResponseParameter = original.AlimTalkMessageResponseParameter
type AlimTalkMessageResponseParameterMessagesItem = original.AlimTalkMessageResponseParameterMessagesItem
type AlimTalkRequestResponseParameter = original.AlimTalkRequestResponseParameter
type AlimTalkRequestResponseParameterMessagesItem = original.AlimTalkRequestResponseParameterMessagesItem
type AlimTalkResultResponseParameter = original.AlimTalkResultResponseParameter
type AlimtalkClient = original.AlimtalkClient
type BaseClient = original.BaseClient
type ChannelClient = original.ChannelClient
type DeviceClient = original.DeviceClient
type MessageClient = original.MessageClient
type PushChannelRequestParameter = original.PushChannelRequestParameter
type PushMessageRequestParameter = original.PushMessageRequestParameter
type PushMessageRequestParameterMessage = original.PushMessageRequestParameterMessage
type PushMessageRequestParameterMessageApns = original.PushMessageRequestParameterMessageApns
type PushMessageRequestParameterMessageApnsI18n = original.PushMessageRequestParameterMessageApnsI18n
type PushMessageRequestParameterMessageApnsI18nDefault = original.PushMessageRequestParameterMessageApnsI18nDefault
type PushMessageRequestParameterMessageApnsI18nlanguage = original.PushMessageRequestParameterMessageApnsI18nlanguage
type PushMessageRequestParameterMessageDefault = original.PushMessageRequestParameterMessageDefault
type PushMessageRequestParameterMessageDefaultI18n = original.PushMessageRequestParameterMessageDefaultI18n
type PushMessageRequestParameterMessageDefaultI18nDefault = original.PushMessageRequestParameterMessageDefaultI18nDefault
type PushMessageRequestParameterMessageDefaultI18nlanguage = original.PushMessageRequestParameterMessageDefaultI18nlanguage
type PushMessageRequestParameterMessageGcm = original.PushMessageRequestParameterMessageGcm
type PushMessageRequestParameterMessageGcmI18n = original.PushMessageRequestParameterMessageGcmI18n
type PushMessageRequestParameterMessageGcmI18nDefault = original.PushMessageRequestParameterMessageGcmI18nDefault
type PushMessageRequestParameterMessageGcmI18nlanguage = original.PushMessageRequestParameterMessageGcmI18nlanguage
type PushMessageRequestParameterTarget = original.PushMessageRequestParameterTarget
type PushMessageResponseParameter = original.PushMessageResponseParameter
type PushMessageResultResponseParameter = original.PushMessageResultResponseParameter
type PushMessageResultResponseParameterMessage = original.PushMessageResultResponseParameterMessage
type PushMessageResultResponseParameterMessageApns = original.PushMessageResultResponseParameterMessageApns
type PushMessageResultResponseParameterMessageApnsI18n = original.PushMessageResultResponseParameterMessageApnsI18n
type PushMessageResultResponseParameterMessageApnsI18nDefault = original.PushMessageResultResponseParameterMessageApnsI18nDefault
type PushMessageResultResponseParameterMessageApnsI18nlanguage = original.PushMessageResultResponseParameterMessageApnsI18nlanguage
type PushMessageResultResponseParameterMessageDefault = original.PushMessageResultResponseParameterMessageDefault
type PushMessageResultResponseParameterMessageDefaultI18n = original.PushMessageResultResponseParameterMessageDefaultI18n
type PushMessageResultResponseParameterMessageDefaultI18nDefault = original.PushMessageResultResponseParameterMessageDefaultI18nDefault
type PushMessageResultResponseParameterMessageDefaultI18nlanguage = original.PushMessageResultResponseParameterMessageDefaultI18nlanguage
type PushMessageResultResponseParameterMessageGcm = original.PushMessageResultResponseParameterMessageGcm
type PushMessageResultResponseParameterMessageGcmI18n = original.PushMessageResultResponseParameterMessageGcmI18n
type PushMessageResultResponseParameterMessageGcmI18nDefault = original.PushMessageResultResponseParameterMessageGcmI18nDefault
type PushMessageResultResponseParameterMessageGcmI18nlanguage = original.PushMessageResultResponseParameterMessageGcmI18nlanguage
type PushMessageResultResponseParameterTarget = original.PushMessageResultResponseParameterTarget
type PushScheduleFetchAllParameter = original.PushScheduleFetchAllParameter
type PushScheduleFetchParameter = original.PushScheduleFetchParameter
type PushScheduleMessageFetchParameter = original.PushScheduleMessageFetchParameter
type PushScheduleRegisterParameter = original.PushScheduleRegisterParameter
type PushUserRequestParameter = original.PushUserRequestParameter
type PushUserResponseParameter = original.PushUserResponseParameter
type PushUserResponseParameterDevicesItem = original.PushUserResponseParameterDevicesItem
type SMSClient = original.SMSClient
type SMSMessage = original.SMSMessage
type SMSMessageParameter = original.SMSMessageParameter
type SMSMessageRequestParameter = original.SMSMessageRequestParameter
type SMSMessageRequestParameterFilesItem = original.SMSMessageRequestParameterFilesItem
type SMSMessageRequestParameterMessagesItem = original.SMSMessageRequestParameterMessagesItem
type ScheduleClient = original.ScheduleClient
type ScheduleMessageClient = original.ScheduleMessageClient

func New() BaseClient {
	return original.New()
}
func NewAlimtalkClient() AlimtalkClient {
	return original.NewAlimtalkClient()
}
func NewAlimtalkClientWithBaseURI(baseURI string) AlimtalkClient {
	return original.NewAlimtalkClientWithBaseURI(baseURI)
}
func NewAlimtalkClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string) AlimtalkClient {
	return original.NewAlimtalkClientWithBaseURIWithKey(baseURI, accessKey, secretKey)
}
func NewAlimtalkClientWithKey(accessKey string, secretKey string) AlimtalkClient {
	return original.NewAlimtalkClientWithKey(accessKey, secretKey)
}
func NewChannelClient() ChannelClient {
	return original.NewChannelClient()
}
func NewChannelClientWithBaseURI(baseURI string) ChannelClient {
	return original.NewChannelClientWithBaseURI(baseURI)
}
func NewChannelClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string) ChannelClient {
	return original.NewChannelClientWithBaseURIWithKey(baseURI, accessKey, secretKey)
}
func NewChannelClientWithKey(accessKey string, secretKey string) ChannelClient {
	return original.NewChannelClientWithKey(accessKey, secretKey)
}
func NewDeviceClient() DeviceClient {
	return original.NewDeviceClient()
}
func NewDeviceClientWithBaseURI(baseURI string) DeviceClient {
	return original.NewDeviceClientWithBaseURI(baseURI)
}
func NewDeviceClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string) DeviceClient {
	return original.NewDeviceClientWithBaseURIWithKey(baseURI, accessKey, secretKey)
}
func NewDeviceClientWithKey(accessKey string, secretKey string) DeviceClient {
	return original.NewDeviceClientWithKey(accessKey, secretKey)
}
func NewMessageClient() MessageClient {
	return original.NewMessageClient()
}
func NewMessageClientWithBaseURI(baseURI string) MessageClient {
	return original.NewMessageClientWithBaseURI(baseURI)
}
func NewMessageClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string) MessageClient {
	return original.NewMessageClientWithBaseURIWithKey(baseURI, accessKey, secretKey)
}
func NewMessageClientWithKey(accessKey string, secretKey string) MessageClient {
	return original.NewMessageClientWithKey(accessKey, secretKey)
}
func NewSMSClient() SMSClient {
	return original.NewSMSClient()
}
func NewSMSClientWithBaseURI(baseURI string) SMSClient {
	return original.NewSMSClientWithBaseURI(baseURI)
}
func NewSMSClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string) SMSClient {
	return original.NewSMSClientWithBaseURIWithKey(baseURI, accessKey, secretKey)
}
func NewSMSClientWithKey(accessKey string, secretKey string) SMSClient {
	return original.NewSMSClientWithKey(accessKey, secretKey)
}
func NewScheduleClient() ScheduleClient {
	return original.NewScheduleClient()
}
func NewScheduleClientWithBaseURI(baseURI string) ScheduleClient {
	return original.NewScheduleClientWithBaseURI(baseURI)
}
func NewScheduleClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string) ScheduleClient {
	return original.NewScheduleClientWithBaseURIWithKey(baseURI, accessKey, secretKey)
}
func NewScheduleClientWithKey(accessKey string, secretKey string) ScheduleClient {
	return original.NewScheduleClientWithKey(accessKey, secretKey)
}
func NewScheduleMessageClient() ScheduleMessageClient {
	return original.NewScheduleMessageClient()
}
func NewScheduleMessageClientWithBaseURI(baseURI string) ScheduleMessageClient {
	return original.NewScheduleMessageClientWithBaseURI(baseURI)
}
func NewScheduleMessageClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string) ScheduleMessageClient {
	return original.NewScheduleMessageClientWithBaseURIWithKey(baseURI, accessKey, secretKey)
}
func NewScheduleMessageClientWithKey(accessKey string, secretKey string) ScheduleMessageClient {
	return original.NewScheduleMessageClientWithKey(accessKey, secretKey)
}
func NewWithBaseURI(baseURI string) BaseClient {
	return original.NewWithBaseURI(baseURI)
}
func NewWithBaseURIWithKey(baseURI string, accessKey string, secretKey string) BaseClient {
	return original.NewWithBaseURIWithKey(baseURI, accessKey, secretKey)
}
func NewWithKey(accessKey string, secretKey string) BaseClient {
	return original.NewWithKey(accessKey, secretKey)
}
func UserAgent() string {
	return original.UserAgent() + " profiles/latest"
}
func Version() string {
	return original.Version()
}
