// +build go1.9

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/samjegal/fincloud-sdk-for-go/tools/profileBuilder

package cloudinsight

import original "github.com/samjegal/fincloud-sdk-for-go/services/cloudinsight"

const (
	DefaultBaseURI = original.DefaultBaseURI
)

type AggregationType = original.AggregationType

const (
	AVG   AggregationType = original.AVG
	COUNT AggregationType = original.COUNT
	MAX   AggregationType = original.MAX
	MIN   AggregationType = original.MIN
	SUM   AggregationType = original.SUM
)

type ChartDataWidgetInfoOption = original.ChartDataWidgetInfoOption

const (
	ChartDataWidgetInfoOptionAVG     ChartDataWidgetInfoOption = original.ChartDataWidgetInfoOptionAVG
	ChartDataWidgetInfoOptionCOUNT   ChartDataWidgetInfoOption = original.ChartDataWidgetInfoOptionCOUNT
	ChartDataWidgetInfoOptionCOUNTER ChartDataWidgetInfoOption = original.ChartDataWidgetInfoOptionCOUNTER
	ChartDataWidgetInfoOptionMAX     ChartDataWidgetInfoOption = original.ChartDataWidgetInfoOptionMAX
	ChartDataWidgetInfoOptionMIN     ChartDataWidgetInfoOption = original.ChartDataWidgetInfoOptionMIN
	ChartDataWidgetInfoOptionSUM     ChartDataWidgetInfoOption = original.ChartDataWidgetInfoOptionSUM
)

type ChartDataWidgetInfoPeriod = original.ChartDataWidgetInfoPeriod

const (
	Day1  ChartDataWidgetInfoPeriod = original.Day1
	Hour2 ChartDataWidgetInfoPeriod = original.Hour2
	Min1  ChartDataWidgetInfoPeriod = original.Min1
	Min30 ChartDataWidgetInfoPeriod = original.Min30
	Min5  ChartDataWidgetInfoPeriod = original.Min5
)

type ChartDataWidgetInfoStatistic = original.ChartDataWidgetInfoStatistic

const (
	ChartDataWidgetInfoStatisticAVG     ChartDataWidgetInfoStatistic = original.ChartDataWidgetInfoStatisticAVG
	ChartDataWidgetInfoStatisticCOUNT   ChartDataWidgetInfoStatistic = original.ChartDataWidgetInfoStatisticCOUNT
	ChartDataWidgetInfoStatisticCOUNTER ChartDataWidgetInfoStatistic = original.ChartDataWidgetInfoStatisticCOUNTER
	ChartDataWidgetInfoStatisticMAX     ChartDataWidgetInfoStatistic = original.ChartDataWidgetInfoStatisticMAX
	ChartDataWidgetInfoStatisticMIN     ChartDataWidgetInfoStatistic = original.ChartDataWidgetInfoStatisticMIN
	ChartDataWidgetInfoStatisticSUM     ChartDataWidgetInfoStatistic = original.ChartDataWidgetInfoStatisticSUM
)

type ChartDataWidgetType = original.ChartDataWidgetType

const (
	Area  ChartDataWidgetType = original.Area
	Index ChartDataWidgetType = original.Index
	Line  ChartDataWidgetType = original.Line
	Table ChartDataWidgetType = original.Table
	Text  ChartDataWidgetType = original.Text
)

type DimensionType = original.DimensionType

const (
	Agent         DimensionType = original.Agent
	CPU           DimensionType = original.CPU
	Disk          DimensionType = original.Disk
	Fs            DimensionType = original.Fs
	Memory        DimensionType = original.Memory
	Ntwk          DimensionType = original.Ntwk
	PluginFile    DimensionType = original.PluginFile
	PluginPort    DimensionType = original.PluginPort
	PluginProcess DimensionType = original.PluginProcess
	Process       DimensionType = original.Process
	Svr           DimensionType = original.Svr
)

type MetricsGroupItemCalculation = original.MetricsGroupItemCalculation

const (
	MetricsGroupItemCalculationAVG     MetricsGroupItemCalculation = original.MetricsGroupItemCalculationAVG
	MetricsGroupItemCalculationCOUNT   MetricsGroupItemCalculation = original.MetricsGroupItemCalculationCOUNT
	MetricsGroupItemCalculationCOUNTER MetricsGroupItemCalculation = original.MetricsGroupItemCalculationCOUNTER
	MetricsGroupItemCalculationMAX     MetricsGroupItemCalculation = original.MetricsGroupItemCalculationMAX
	MetricsGroupItemCalculationMIN     MetricsGroupItemCalculation = original.MetricsGroupItemCalculationMIN
	MetricsGroupItemCalculationSUM     MetricsGroupItemCalculation = original.MetricsGroupItemCalculationSUM
)

type MetricsGroupItemCondition = original.MetricsGroupItemCondition

const (
	EQ  MetricsGroupItemCondition = original.EQ
	EXP MetricsGroupItemCondition = original.EXP
	GE  MetricsGroupItemCondition = original.GE
	GT  MetricsGroupItemCondition = original.GT
	LE  MetricsGroupItemCondition = original.LE
	LT  MetricsGroupItemCondition = original.LT
	NE  MetricsGroupItemCondition = original.NE
)

type MetricsGroupItemEventLevel = original.MetricsGroupItemEventLevel

const (
	CRITICAL MetricsGroupItemEventLevel = original.CRITICAL
	INFO     MetricsGroupItemEventLevel = original.INFO
	WARNING  MetricsGroupItemEventLevel = original.WARNING
)

type QueryAggregationType = original.QueryAggregationType

const (
	QueryAggregationTypeAVG   QueryAggregationType = original.QueryAggregationTypeAVG
	QueryAggregationTypeCOUNT QueryAggregationType = original.QueryAggregationTypeCOUNT
	QueryAggregationTypeFIRST QueryAggregationType = original.QueryAggregationTypeFIRST
	QueryAggregationTypeLAST  QueryAggregationType = original.QueryAggregationTypeLAST
	QueryAggregationTypeMAX   QueryAggregationType = original.QueryAggregationTypeMAX
	QueryAggregationTypeMIN   QueryAggregationType = original.QueryAggregationTypeMIN
	QueryAggregationTypeMULT  QueryAggregationType = original.QueryAggregationTypeMULT
	QueryAggregationTypeNONE  QueryAggregationType = original.QueryAggregationTypeNONE
	QueryAggregationTypeSUM   QueryAggregationType = original.QueryAggregationTypeSUM
)

type QueryIntervalTime = original.QueryIntervalTime

const (
	DAY1  QueryIntervalTime = original.DAY1
	HOUR2 QueryIntervalTime = original.HOUR2
	MIN1  QueryIntervalTime = original.MIN1
	MIN30 QueryIntervalTime = original.MIN30
	MIN5  QueryIntervalTime = original.MIN5
)

type RecipientNotificationNotifyType = original.RecipientNotificationNotifyType

const (
	EMAIL RecipientNotificationNotifyType = original.EMAIL
	SMS   RecipientNotificationNotifyType = original.SMS
)

type RuleGroupProductDataStatus = original.RuleGroupProductDataStatus

const (
	CREATED RuleGroupProductDataStatus = original.CREATED
	DELETED RuleGroupProductDataStatus = original.DELETED
	UPDATED RuleGroupProductDataStatus = original.UPDATED
)

type RuleGroupStatus = original.RuleGroupStatus

const (
	INSUFFICIENT RuleGroupStatus = original.INSUFFICIENT
	OK           RuleGroupStatus = original.OK
	VIOLATED     RuleGroupStatus = original.VIOLATED
)

type RuleGroupVersion = original.RuleGroupVersion

const (
	V1 RuleGroupVersion = original.V1
	V2 RuleGroupVersion = original.V2
)

type SchemaFieldDataType = original.SchemaFieldDataType

const (
	ARRAY     SchemaFieldDataType = original.ARRAY
	FLOAT     SchemaFieldDataType = original.FLOAT
	INTEGER   SchemaFieldDataType = original.INTEGER
	LONG      SchemaFieldDataType = original.LONG
	STRING    SchemaFieldDataType = original.STRING
	TIMESTAMP SchemaFieldDataType = original.TIMESTAMP
)

type SchemaFieldDimensionType = original.SchemaFieldDimensionType

const (
	CUSTOM  SchemaFieldDimensionType = original.CUSTOM
	DEFAULT SchemaFieldDimensionType = original.DEFAULT
)

type SchemaFieldMetricType = original.SchemaFieldMetricType

const (
	SchemaFieldMetricTypeBASIC    SchemaFieldMetricType = original.SchemaFieldMetricTypeBASIC
	SchemaFieldMetricTypeCUSTOM   SchemaFieldMetricType = original.SchemaFieldMetricTypeCUSTOM
	SchemaFieldMetricTypeEXTENDED SchemaFieldMetricType = original.SchemaFieldMetricTypeEXTENDED
)

type SchemaFieldaAggregation = original.SchemaFieldaAggregation

const (
	SchemaFieldaAggregationAVG     SchemaFieldaAggregation = original.SchemaFieldaAggregationAVG
	SchemaFieldaAggregationCOUNT   SchemaFieldaAggregation = original.SchemaFieldaAggregationCOUNT
	SchemaFieldaAggregationCOUNTER SchemaFieldaAggregation = original.SchemaFieldaAggregationCOUNTER
	SchemaFieldaAggregationMAX     SchemaFieldaAggregation = original.SchemaFieldaAggregationMAX
	SchemaFieldaAggregationMIN     SchemaFieldaAggregation = original.SchemaFieldaAggregationMIN
	SchemaFieldaAggregationSUM     SchemaFieldaAggregation = original.SchemaFieldaAggregationSUM
)

type SeverTargetMetric = original.SeverTargetMetric

const (
	AvgCPUUsedRto SeverTargetMetric = original.AvgCPUUsedRto
	AvgFsUsert    SeverTargetMetric = original.AvgFsUsert
	MemUsert      SeverTargetMetric = original.MemUsert
)

type WidgetMetricInfoPeriod = original.WidgetMetricInfoPeriod

const (
	WidgetMetricInfoPeriodDay1  WidgetMetricInfoPeriod = original.WidgetMetricInfoPeriodDay1
	WidgetMetricInfoPeriodHour2 WidgetMetricInfoPeriod = original.WidgetMetricInfoPeriodHour2
	WidgetMetricInfoPeriodMin1  WidgetMetricInfoPeriod = original.WidgetMetricInfoPeriodMin1
	WidgetMetricInfoPeriodMin30 WidgetMetricInfoPeriod = original.WidgetMetricInfoPeriodMin30
	WidgetMetricInfoPeriodMin5  WidgetMetricInfoPeriod = original.WidgetMetricInfoPeriodMin5
)

type WidgetMetricInfoQueryAggregation = original.WidgetMetricInfoQueryAggregation

const (
	WidgetMetricInfoQueryAggregationAVG    WidgetMetricInfoQueryAggregation = original.WidgetMetricInfoQueryAggregationAVG
	WidgetMetricInfoQueryAggregationCOUNT  WidgetMetricInfoQueryAggregation = original.WidgetMetricInfoQueryAggregationCOUNT
	WidgetMetricInfoQueryAggregationFIRST  WidgetMetricInfoQueryAggregation = original.WidgetMetricInfoQueryAggregationFIRST
	WidgetMetricInfoQueryAggregationLAST   WidgetMetricInfoQueryAggregation = original.WidgetMetricInfoQueryAggregationLAST
	WidgetMetricInfoQueryAggregationMAX    WidgetMetricInfoQueryAggregation = original.WidgetMetricInfoQueryAggregationMAX
	WidgetMetricInfoQueryAggregationMIMMAX WidgetMetricInfoQueryAggregation = original.WidgetMetricInfoQueryAggregationMIMMAX
	WidgetMetricInfoQueryAggregationMIMMIN WidgetMetricInfoQueryAggregation = original.WidgetMetricInfoQueryAggregationMIMMIN
	WidgetMetricInfoQueryAggregationMIN    WidgetMetricInfoQueryAggregation = original.WidgetMetricInfoQueryAggregationMIN
	WidgetMetricInfoQueryAggregationMULT   WidgetMetricInfoQueryAggregation = original.WidgetMetricInfoQueryAggregationMULT
	WidgetMetricInfoQueryAggregationNONE   WidgetMetricInfoQueryAggregation = original.WidgetMetricInfoQueryAggregationNONE
	WidgetMetricInfoQueryAggregationSUM    WidgetMetricInfoQueryAggregation = original.WidgetMetricInfoQueryAggregationSUM
	WidgetMetricInfoQueryAggregationZIMSUM WidgetMetricInfoQueryAggregation = original.WidgetMetricInfoQueryAggregationZIMSUM
)

type WidgetMetricInfoStatistic = original.WidgetMetricInfoStatistic

const (
	WidgetMetricInfoStatisticAVG     WidgetMetricInfoStatistic = original.WidgetMetricInfoStatisticAVG
	WidgetMetricInfoStatisticCOUNT   WidgetMetricInfoStatistic = original.WidgetMetricInfoStatisticCOUNT
	WidgetMetricInfoStatisticCOUNTER WidgetMetricInfoStatistic = original.WidgetMetricInfoStatisticCOUNTER
	WidgetMetricInfoStatisticMAX     WidgetMetricInfoStatistic = original.WidgetMetricInfoStatisticMAX
	WidgetMetricInfoStatisticMIN     WidgetMetricInfoStatistic = original.WidgetMetricInfoStatisticMIN
	WidgetMetricInfoStatisticSUM     WidgetMetricInfoStatistic = original.WidgetMetricInfoStatisticSUM
)

type AsgPolicyParameter = original.AsgPolicyParameter
type BaseClient = original.BaseClient
type ChartClient = original.ChartClient
type ChartDataWidgetRequest = original.ChartDataWidgetRequest
type CollectorClient = original.CollectorClient
type CollectorRequest = original.CollectorRequest
type CollectorResponse = original.CollectorResponse
type DataClient = original.DataClient
type DimensionItemParameter = original.DimensionItemParameter
type DimensionParameter = original.DimensionParameter
type DimensionResultParameter = original.DimensionResultParameter
type DirectRuleGroupCreateRequest = original.DirectRuleGroupCreateRequest
type EventClient = original.EventClient
type EventRuleResponse = original.EventRuleResponse
type EventSearchDimensionParameter = original.EventSearchDimensionParameter
type EventSearchRequest = original.EventSearchRequest
type EventSearchResultParameter = original.EventSearchResultParameter
type ExtendedClient = original.ExtendedClient
type FilePluginClient = original.FilePluginClient
type FilePluginDetailResponse = original.FilePluginDetailResponse
type FilePluginParameter = original.FilePluginParameter
type FilePluginRequest = original.FilePluginRequest
type Int64 = original.Int64
type ListEventSearchResultParameter = original.ListEventSearchResultParameter
type ListFilePluginParameter = original.ListFilePluginParameter
type ListInt64 = original.ListInt64
type ListListFloat64 = original.ListListFloat64
type ListMonitorGroupParameter = original.ListMonitorGroupParameter
type ListMultipleDataParameter = original.ListMultipleDataParameter
type ListPortPluginParameter = original.ListPortPluginParameter
type ListProcessPluginParameter = original.ListProcessPluginParameter
type ListRuleGroupItemListParameter = original.ListRuleGroupItemListParameter
type ListSchemaExtendedStatusParameter = original.ListSchemaExtendedStatusParameter
type ListServerTopMetricParameter = original.ListServerTopMetricParameter
type ListSetObject = original.ListSetObject
type ListString = original.ListString
type MetricClient = original.MetricClient
type MetricGroupClient = original.MetricGroupClient
type MetricGroupListResponse = original.MetricGroupListResponse
type MetricInfoParameter = original.MetricInfoParameter
type MetricListRequest = original.MetricListRequest
type MetricsGroupCreateorUpdateParameter = original.MetricsGroupCreateorUpdateParameter
type MetricsGroupItemParameter = original.MetricsGroupItemParameter
type MetricsGroupParameter = original.MetricsGroupParameter
type MetricsGroupRequest = original.MetricsGroupRequest
type MonitorClient = original.MonitorClient
type MonitorGroupClient = original.MonitorGroupClient
type MonitorGroupItemParameter = original.MonitorGroupItemParameter
type MonitorGroupParameter = original.MonitorGroupParameter
type MonitorGroupRequest = original.MonitorGroupRequest
type MultipleDataParameter = original.MultipleDataParameter
type NotificationClient = original.NotificationClient
type PortPluginClient = original.PortPluginClient
type PortPluginDetailResponse = original.PortPluginDetailResponse
type PortPluginParameter = original.PortPluginParameter
type PortPluginRequest = original.PortPluginRequest
type ProcessPluginClient = original.ProcessPluginClient
type ProcessPluginDetailResponse = original.ProcessPluginDetailResponse
type ProcessPluginParameter = original.ProcessPluginParameter
type ProcessPluginRequest = original.ProcessPluginRequest
type QueryMultipleRequest = original.QueryMultipleRequest
type QueryRequest = original.QueryRequest
type RecipientNotificationParameter = original.RecipientNotificationParameter
type RemoveResourceFromRulesParameter = original.RemoveResourceFromRulesParameter
type RuleGroup = original.RuleGroup
type RuleGroupClient = original.RuleGroupClient
type RuleGroupCopyForAsgGroupRequest = original.RuleGroupCopyForAsgGroupRequest
type RuleGroupCopySettingRequest = original.RuleGroupCopySettingRequest
type RuleGroupDeleteItemParameter = original.RuleGroupDeleteItemParameter
type RuleGroupDeleteRequest = original.RuleGroupDeleteRequest
type RuleGroupItemListParameter = original.RuleGroupItemListParameter
type RuleGroupItemParameter = original.RuleGroupItemParameter
type RuleGroupListQueryRequest = original.RuleGroupListQueryRequest
type RuleGroupListQueryResponse = original.RuleGroupListQueryResponse
type RuleGroupParameter = original.RuleGroupParameter
type RuleGroupRequest = original.RuleGroupRequest
type ScehmaUpdateResponse = original.ScehmaUpdateResponse
type SchemaClient = original.SchemaClient
type SchemaExtendedDisableResponse = original.SchemaExtendedDisableResponse
type SchemaExtendedEnableResponse = original.SchemaExtendedEnableResponse
type SchemaExtendedStatusParameter = original.SchemaExtendedStatusParameter
type SchemaFieldParameter = original.SchemaFieldParameter
type SchemaFieldRequestParameter = original.SchemaFieldRequestParameter
type SchemaRegisterResponse = original.SchemaRegisterResponse
type SchemaRequest = original.SchemaRequest
type SchemaResponse = original.SchemaResponse
type SearchEventCountConsoleRequest = original.SearchEventCountConsoleRequest
type SearchEventCountConsoleResponse = original.SearchEventCountConsoleResponse
type ServerClient = original.ServerClient
type ServerTopMetricParameter = original.ServerTopMetricParameter
type String = original.String
type SuspendRuleItemParameter = original.SuspendRuleItemParameter
type TypeGroupRelatedRuleParameter = original.TypeGroupRelatedRuleParameter
type WidgetMetricInfoParameter = original.WidgetMetricInfoParameter
type WidgetMetricInfoResponse = original.WidgetMetricInfoResponse

func New() BaseClient {
	return original.New()
}
func NewChartClient() ChartClient {
	return original.NewChartClient()
}
func NewChartClientWithBaseURI(baseURI string) ChartClient {
	return original.NewChartClientWithBaseURI(baseURI)
}
func NewChartClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) ChartClient {
	return original.NewChartClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewChartClientWithKey(accessKey string, secretKey string, apiGatewayKey string) ChartClient {
	return original.NewChartClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewCollectorClient() CollectorClient {
	return original.NewCollectorClient()
}
func NewCollectorClientWithBaseURI(baseURI string) CollectorClient {
	return original.NewCollectorClientWithBaseURI(baseURI)
}
func NewCollectorClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) CollectorClient {
	return original.NewCollectorClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewCollectorClientWithKey(accessKey string, secretKey string, apiGatewayKey string) CollectorClient {
	return original.NewCollectorClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewDataClient() DataClient {
	return original.NewDataClient()
}
func NewDataClientWithBaseURI(baseURI string) DataClient {
	return original.NewDataClientWithBaseURI(baseURI)
}
func NewDataClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) DataClient {
	return original.NewDataClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewDataClientWithKey(accessKey string, secretKey string, apiGatewayKey string) DataClient {
	return original.NewDataClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewEventClient() EventClient {
	return original.NewEventClient()
}
func NewEventClientWithBaseURI(baseURI string) EventClient {
	return original.NewEventClientWithBaseURI(baseURI)
}
func NewEventClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) EventClient {
	return original.NewEventClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewEventClientWithKey(accessKey string, secretKey string, apiGatewayKey string) EventClient {
	return original.NewEventClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewExtendedClient() ExtendedClient {
	return original.NewExtendedClient()
}
func NewExtendedClientWithBaseURI(baseURI string) ExtendedClient {
	return original.NewExtendedClientWithBaseURI(baseURI)
}
func NewExtendedClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) ExtendedClient {
	return original.NewExtendedClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewExtendedClientWithKey(accessKey string, secretKey string, apiGatewayKey string) ExtendedClient {
	return original.NewExtendedClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewFilePluginClient() FilePluginClient {
	return original.NewFilePluginClient()
}
func NewFilePluginClientWithBaseURI(baseURI string) FilePluginClient {
	return original.NewFilePluginClientWithBaseURI(baseURI)
}
func NewFilePluginClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) FilePluginClient {
	return original.NewFilePluginClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewFilePluginClientWithKey(accessKey string, secretKey string, apiGatewayKey string) FilePluginClient {
	return original.NewFilePluginClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewMetricClient() MetricClient {
	return original.NewMetricClient()
}
func NewMetricClientWithBaseURI(baseURI string) MetricClient {
	return original.NewMetricClientWithBaseURI(baseURI)
}
func NewMetricClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) MetricClient {
	return original.NewMetricClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewMetricClientWithKey(accessKey string, secretKey string, apiGatewayKey string) MetricClient {
	return original.NewMetricClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewMetricGroupClient() MetricGroupClient {
	return original.NewMetricGroupClient()
}
func NewMetricGroupClientWithBaseURI(baseURI string) MetricGroupClient {
	return original.NewMetricGroupClientWithBaseURI(baseURI)
}
func NewMetricGroupClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) MetricGroupClient {
	return original.NewMetricGroupClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewMetricGroupClientWithKey(accessKey string, secretKey string, apiGatewayKey string) MetricGroupClient {
	return original.NewMetricGroupClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewMonitorClient() MonitorClient {
	return original.NewMonitorClient()
}
func NewMonitorClientWithBaseURI(baseURI string) MonitorClient {
	return original.NewMonitorClientWithBaseURI(baseURI)
}
func NewMonitorClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) MonitorClient {
	return original.NewMonitorClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewMonitorClientWithKey(accessKey string, secretKey string, apiGatewayKey string) MonitorClient {
	return original.NewMonitorClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewMonitorGroupClient() MonitorGroupClient {
	return original.NewMonitorGroupClient()
}
func NewMonitorGroupClientWithBaseURI(baseURI string) MonitorGroupClient {
	return original.NewMonitorGroupClientWithBaseURI(baseURI)
}
func NewMonitorGroupClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) MonitorGroupClient {
	return original.NewMonitorGroupClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewMonitorGroupClientWithKey(accessKey string, secretKey string, apiGatewayKey string) MonitorGroupClient {
	return original.NewMonitorGroupClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewNotificationClient() NotificationClient {
	return original.NewNotificationClient()
}
func NewNotificationClientWithBaseURI(baseURI string) NotificationClient {
	return original.NewNotificationClientWithBaseURI(baseURI)
}
func NewNotificationClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) NotificationClient {
	return original.NewNotificationClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewNotificationClientWithKey(accessKey string, secretKey string, apiGatewayKey string) NotificationClient {
	return original.NewNotificationClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewPortPluginClient() PortPluginClient {
	return original.NewPortPluginClient()
}
func NewPortPluginClientWithBaseURI(baseURI string) PortPluginClient {
	return original.NewPortPluginClientWithBaseURI(baseURI)
}
func NewPortPluginClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) PortPluginClient {
	return original.NewPortPluginClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewPortPluginClientWithKey(accessKey string, secretKey string, apiGatewayKey string) PortPluginClient {
	return original.NewPortPluginClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewProcessPluginClient() ProcessPluginClient {
	return original.NewProcessPluginClient()
}
func NewProcessPluginClientWithBaseURI(baseURI string) ProcessPluginClient {
	return original.NewProcessPluginClientWithBaseURI(baseURI)
}
func NewProcessPluginClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) ProcessPluginClient {
	return original.NewProcessPluginClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewProcessPluginClientWithKey(accessKey string, secretKey string, apiGatewayKey string) ProcessPluginClient {
	return original.NewProcessPluginClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewRuleGroupClient() RuleGroupClient {
	return original.NewRuleGroupClient()
}
func NewRuleGroupClientWithBaseURI(baseURI string) RuleGroupClient {
	return original.NewRuleGroupClientWithBaseURI(baseURI)
}
func NewRuleGroupClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) RuleGroupClient {
	return original.NewRuleGroupClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewRuleGroupClientWithKey(accessKey string, secretKey string, apiGatewayKey string) RuleGroupClient {
	return original.NewRuleGroupClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewSchemaClient() SchemaClient {
	return original.NewSchemaClient()
}
func NewSchemaClientWithBaseURI(baseURI string) SchemaClient {
	return original.NewSchemaClientWithBaseURI(baseURI)
}
func NewSchemaClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) SchemaClient {
	return original.NewSchemaClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewSchemaClientWithKey(accessKey string, secretKey string, apiGatewayKey string) SchemaClient {
	return original.NewSchemaClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewServerClient() ServerClient {
	return original.NewServerClient()
}
func NewServerClientWithBaseURI(baseURI string) ServerClient {
	return original.NewServerClientWithBaseURI(baseURI)
}
func NewServerClientWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) ServerClient {
	return original.NewServerClientWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewServerClientWithKey(accessKey string, secretKey string, apiGatewayKey string) ServerClient {
	return original.NewServerClientWithKey(accessKey, secretKey, apiGatewayKey)
}
func NewWithBaseURI(baseURI string) BaseClient {
	return original.NewWithBaseURI(baseURI)
}
func NewWithBaseURIWithKey(baseURI string, accessKey string, secretKey string, apiGatewayKey string) BaseClient {
	return original.NewWithBaseURIWithKey(baseURI, accessKey, secretKey, apiGatewayKey)
}
func NewWithKey(accessKey string, secretKey string, apiGatewayKey string) BaseClient {
	return original.NewWithKey(accessKey, secretKey, apiGatewayKey)
}
func PossibleAggregationTypeValues() []AggregationType {
	return original.PossibleAggregationTypeValues()
}
func PossibleChartDataWidgetInfoOptionValues() []ChartDataWidgetInfoOption {
	return original.PossibleChartDataWidgetInfoOptionValues()
}
func PossibleChartDataWidgetInfoPeriodValues() []ChartDataWidgetInfoPeriod {
	return original.PossibleChartDataWidgetInfoPeriodValues()
}
func PossibleChartDataWidgetInfoStatisticValues() []ChartDataWidgetInfoStatistic {
	return original.PossibleChartDataWidgetInfoStatisticValues()
}
func PossibleChartDataWidgetTypeValues() []ChartDataWidgetType {
	return original.PossibleChartDataWidgetTypeValues()
}
func PossibleDimensionTypeValues() []DimensionType {
	return original.PossibleDimensionTypeValues()
}
func PossibleMetricsGroupItemCalculationValues() []MetricsGroupItemCalculation {
	return original.PossibleMetricsGroupItemCalculationValues()
}
func PossibleMetricsGroupItemConditionValues() []MetricsGroupItemCondition {
	return original.PossibleMetricsGroupItemConditionValues()
}
func PossibleMetricsGroupItemEventLevelValues() []MetricsGroupItemEventLevel {
	return original.PossibleMetricsGroupItemEventLevelValues()
}
func PossibleQueryAggregationTypeValues() []QueryAggregationType {
	return original.PossibleQueryAggregationTypeValues()
}
func PossibleQueryIntervalTimeValues() []QueryIntervalTime {
	return original.PossibleQueryIntervalTimeValues()
}
func PossibleRecipientNotificationNotifyTypeValues() []RecipientNotificationNotifyType {
	return original.PossibleRecipientNotificationNotifyTypeValues()
}
func PossibleRuleGroupProductDataStatusValues() []RuleGroupProductDataStatus {
	return original.PossibleRuleGroupProductDataStatusValues()
}
func PossibleRuleGroupStatusValues() []RuleGroupStatus {
	return original.PossibleRuleGroupStatusValues()
}
func PossibleRuleGroupVersionValues() []RuleGroupVersion {
	return original.PossibleRuleGroupVersionValues()
}
func PossibleSchemaFieldDataTypeValues() []SchemaFieldDataType {
	return original.PossibleSchemaFieldDataTypeValues()
}
func PossibleSchemaFieldDimensionTypeValues() []SchemaFieldDimensionType {
	return original.PossibleSchemaFieldDimensionTypeValues()
}
func PossibleSchemaFieldMetricTypeValues() []SchemaFieldMetricType {
	return original.PossibleSchemaFieldMetricTypeValues()
}
func PossibleSchemaFieldaAggregationValues() []SchemaFieldaAggregation {
	return original.PossibleSchemaFieldaAggregationValues()
}
func PossibleSeverTargetMetricValues() []SeverTargetMetric {
	return original.PossibleSeverTargetMetricValues()
}
func PossibleWidgetMetricInfoPeriodValues() []WidgetMetricInfoPeriod {
	return original.PossibleWidgetMetricInfoPeriodValues()
}
func PossibleWidgetMetricInfoQueryAggregationValues() []WidgetMetricInfoQueryAggregation {
	return original.PossibleWidgetMetricInfoQueryAggregationValues()
}
func PossibleWidgetMetricInfoStatisticValues() []WidgetMetricInfoStatistic {
	return original.PossibleWidgetMetricInfoStatisticValues()
}
func UserAgent() string {
	return original.UserAgent() + " profiles/latest"
}
func Version() string {
	return original.Version()
}
